server:
  port: ${PORT:8080}

app:
  public-url: ${APP_PUBLIC_URL:http://localhost:8080}
  cors-origins: ${APP_CORS_ORIGINS:http://localhost:5173}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/civicpulse?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect   # Good to add

  sql:
    init:
      mode: always